# Generated by Django 5.1.1 on 2024-10-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
