# Generated by Django 5.1.1 on 2024-09-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0002_remove_institutions_create_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=225)),
                ('suscription_date', models.DateField()),
                ('suscription_type', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('number_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='institutions',
        ),
    ]
