# Generated by Django 5.1.1 on 2024-10-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0002_institution_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='name',
            new_name='username',
        ),
    ]
