# Generated by Django 5.1.1 on 2024-10-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0003_rename_name_institution_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
