# Generated by Django 5.1.1 on 2024-10-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0004_alter_institution_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='authorization',
            field=models.BooleanField(default=False),
        ),
    ]
