# Generated by Django 5.1.1 on 2024-09-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0004_institution_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='suscription_type',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
