# Generated by Django 5.1.1 on 2024-09-24 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0005_alter_institution_suscription_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='suscription_date',
        ),
        migrations.AddField(
            model_name='institution',
            name='subscription_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
