# Generated by Django 5.1.1 on 2024-10-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0005_institution_authorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='authorization',
            field=models.BooleanField(default=True),
        ),
    ]
