# Generated by Django 5.1.1 on 2024-09-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0006_remove_institution_suscription_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='suscription_type',
            field=models.CharField(max_length=50),
        ),
    ]
