# Generated by Django 5.1.1 on 2024-09-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0007_alter_institution_suscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
