<<<<<<< HEAD
# Generated by Django 5.1.1 on 2024-09-26 14:28
=======
# Generated by Django 5.1.1 on 2024-09-26 14:19
>>>>>>> 89cd290361fac9c9f1465aff239501228dfbcf4e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0008_institution_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
