# Generated by Django 5.1.1 on 2024-09-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0009_institution_imagen_url_alter_institution_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='image',
        ),
        migrations.AddField(
            model_name='institution',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
