# Generated by Django 5.1.1 on 2024-09-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0014_alter_institution_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='subscription_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
