# Generated by Django 5.1.1 on 2024-09-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0015_alter_institution_subscription_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='imagen',
        ),
    ]
