services:
  react:
    container_name: gui_front_end
    image: gui_front_end
    build:
      context: ./Gui_front_end
    volumes:
      - ./Gui_front_end:/app
      - /app/node_modules
    ports:
      - "5173:5173"
  django:
    image: gui_backend
    container_name: gui_backend
    build:
      context: ./Gui_backend
    ports:
      - "8000:8000"
    volumes:
      - ./Gui_backend:/app
    command: ["./wait-for-it.sh", "-t", "30", "mysql:3306", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Gui
    volumes:
      - django_react_data:/data/db
      - ./dumps:/docker-entrypoint-initdb.d:ro
volumes:
  django_react_data: