# Generated by Django 5.1.1 on 2024-09-29 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0007_remove_staff_imagen_remove_staff_imagen_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='teaching_assistance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=225)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
    ]
