# Generated by Django 5.1.1 on 2024-09-29 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_assistance', '0001_initial'),
        ('students', '0005_alter_students_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_assistance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Present', 'present'), ('Absent ', 'absent')], max_length=225)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
        ),
        migrations.DeleteModel(
            name='teaching_assistance',
        ),
    ]
