# Generated by Django 5.1.1 on 2024-09-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_assistance', '0002_student_assistance_delete_teaching_assistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_assistance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
