# Generated by Django 5.1.1 on 2024-10-27 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_assistance', '0002_remove_student_assistance_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_assistance',
            old_name='staff',
            new_name='student',
        ),
    ]
