# Generated by Django 5.1.1 on 2024-10-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_assistance', '0003_rename_staff_student_assistance_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_assistance',
            name='dateToday',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
