# Generated by Django 5.1.1 on 2024-10-27 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_staff_authorization'),
        ('student_assistance', '0004_student_assistance_datetoday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_assistance',
            name='student',
        ),
        migrations.AddField(
            model_name='student_assistance',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
            preserve_default=False,
        ),
    ]
