# Generated by Django 5.1.1 on 2024-10-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_gui',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
