# Generated by Django 5.1.1 on 2024-10-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gui', '0002_admin_gui_is_authorized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_gui',
            name='is_authorized',
        ),
    ]
