# Generated by Django 5.1.1 on 2024-10-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gui', '0003_remove_admin_gui_is_authorized'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_gui',
            old_name='nombre',
            new_name='username',
        ),
        migrations.AddField(
            model_name='admin_gui',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
