# Generated by Django 5.1.1 on 2024-09-26 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='subject_name',
            new_name='name',
        ),
    ]
