# Generated by Django 5.1.1 on 2024-09-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_rename_subject_name_subjects_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='name',
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_group',
            field=models.JSONField(default=2),
            preserve_default=False,
        ),
    ]
