# Generated by Django 5.1.1 on 2024-09-30 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_alter_students_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.CharField(max_length=225)),
                ('amount', models.CharField(max_length=225)),
                ('payment_type', models.CharField(max_length=225)),
                ('payment_status', models.CharField(max_length=225)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
        ),
    ]
