# Generated by Django 5.1.1 on 2024-09-30 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0007_remove_staff_imagen_remove_staff_imagen_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to='staff.staff')),
                ('transmitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='staff.staff')),
            ],
        ),
    ]
