# Generated by Django 5.1.1 on 2024-10-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_remove_message_date_alter_message_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender_name',
        ),
    ]
