# Generated by Django 5.1.1 on 2024-10-15 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_alter_message_receiver_alter_message_transmitter'),
        ('staff', '0008_alter_staff_password'),
        ('students', '0004_alter_students_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='transmitter',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_received_staff', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_received_students', to='students.students'),
        ),
        migrations.AddField(
            model_name='message',
            name='transmitter_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent_staff', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='message',
            name='transmitter_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent_students', to='students.students'),
        ),
    ]
