# Generated by Django 5.1.1 on 2024-10-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0011_remove_message_transmitter_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='transmitter_staff',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='transmitter_student',
            new_name='students',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver_staff',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver_student',
        ),
    ]
