# Generated by Django 5.1.1 on 2024-10-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0013_message_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
    ]
