# Generated by Django 5.1.1 on 2024-10-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
