# Generated by Django 5.1.1 on 2024-10-03 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='subjects',
        ),
    ]
