# Generated by Django 5.1.1 on 2024-09-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_school_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='school_subjects',
        ),
    ]
