# Generated by Django 5.1.1 on 2024-10-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_staff_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='imagen_url',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
