# Generated by Django 5.1.1 on 2024-09-27 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0003_remove_subjects_institution_remove_subjects_name_and_more'),
        ('staff', '0003_remove_staff_school_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materias.subjects'),
        ),
    ]
