# Generated by Django 5.1.1 on 2024-09-28 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_rename_institution_contracts_institution_and_more'),
        ('staff', '0004_alter_staff_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_contracts', to='contracts.contracts'),
        ),
    ]
