# Generated by Django 5.1.1 on 2024-10-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staff_imagen_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='username',
        ),
    ]
