# Generated by Django 5.1.1 on 2024-09-29 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staff_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='birthdate_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
