# Generated by Django 5.1.1 on 2024-10-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_rename_name_staff_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
