# Generated by Django 5.1.1 on 2024-10-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_staff_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='authorization',
            field=models.BooleanField(default=False),
        ),
    ]
