# Generated by Django 5.1.1 on 2024-10-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_staff_authorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_teacher',
            field=models.BooleanField(default=True),
        ),
    ]
