# Generated by Django 5.1.1 on 2024-10-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_subject_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='subject_group',
            field=models.JSONField(null=True),
        ),
    ]
