# Generated by Django 5.1.1 on 2024-09-28 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_group_name_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='group_name',
        ),
    ]
