# Generated by Django 5.1.1 on 2024-09-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_rename_name_group_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='classroom',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
