# Generated by Django 5.1.1 on 2024-10-04 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_subject_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='subject_group',
            new_name='communication_of_subjects_and_teacher',
        ),
    ]
