# Generated by Django 5.1.1 on 2024-10-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_current_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='current_students',
            field=models.IntegerField(blank=True),
        ),
    ]
