# Generated by Django 5.1.1 on 2024-10-21 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_rename_grades_grades_grade_results_and_more'),
        ('staff', '0009_staff_authorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
            preserve_default=False,
        ),
    ]
