# Generated by Django 5.1.1 on 2024-09-26 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grades',
            old_name='perdiod',
            new_name='period',
        ),
    ]
