# Generated by Django 5.1.1 on 2024-09-29 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_rename_perdiod_grades_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grades',
            old_name='subjects',
            new_name='subject',
        ),
    ]
