# Generated by Django 5.1.1 on 2024-10-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_assignment',
            name='registration_day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
