# Generated by Django 5.1.1 on 2024-09-25 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Institucion', '0007_alter_institution_suscription_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('birthdate_date', models.DateField()),
                ('degree', models.CharField(max_length=100)),
                ('academic_status', models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado'), ('graduado', 'Graduado')], max_length=100)),
                ('medic_information', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=100)),
                ('Institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.institution')),
            ],
        ),
    ]
