# Generated by Django 5.1.1 on 2024-09-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contracts',
            old_name='Institution',
            new_name='institution',
        ),
        migrations.AlterField(
            model_name='contracts',
            name='academic_status',
            field=models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive'), ('Graduate', 'graduate')], max_length=100),
        ),
    ]
