# Generated by Django 5.1.1 on 2024-09-30 01:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
        ('students', '0005_alter_students_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parents',
            old_name='end_time',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='parents',
            old_name='start_time',
            new_name='student_association',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='subject',
        ),
        migrations.AddField(
            model_name='parents',
            name='email',
            field=models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='parents',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.students'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parents',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
