# Generated by Django 5.1.1 on 2024-10-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='days',
            field=models.CharField(max_length=100),
        ),
    ]
