# Generated by Django 5.1.1 on 2024-10-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='days',
            field=models.JSONField(),
        ),
    ]
