# Generated by Django 5.1.1 on 2024-09-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_assistance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching_assistance',
            name='status',
            field=models.CharField(choices=[('Present', 'present'), ('Absent ', 'absent')], max_length=225),
        ),
    ]
