# Generated by Django 5.1.1 on 2024-09-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_assistance', '0002_alter_teaching_assistance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching_assistance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
