# Generated by Django 5.1.1 on 2024-09-25 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Institucion', '0008_institution_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('identification_number', models.CharField(max_length=100)),
                ('birthdate_date', models.DateField()),
                ('grade', models.CharField(choices=[('Inactive', 'inactive'), ('Active', 'active'), ('Graduate', 'graduate')], max_length=100)),
                ('academcic_status', models.CharField(max_length=100)),
                ('allergy_information', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.institution')),
            ],
        ),
    ]
