# Generated by Django 5.1.1 on 2024-10-03 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Institucion', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('identification_number', models.CharField(max_length=100)),
                ('birthdate_date', models.DateField()),
                ('grade', models.CharField(choices=[('1st Grade', '1st Grade'), ('2nd Grade', '2nd Grade'), ('3rd Grade', '3rd Grade'), ('4th Grade', '4th Grade'), ('5th Grade', '5th Grade'), ('6th Grade', '6th Grade')], max_length=100)),
                ('academic_status', models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], max_length=100)),
                ('allergy_information', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('guardian_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('name_guardian', models.CharField(max_length=100)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('monthly_payent_students', models.CharField(blank=True, max_length=15, null=True)),
                ('type_of_student', models.CharField(choices=[('private student', 'private student'), ('student care network', 'student care network')], default='private student', max_length=100)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Institucion.institution')),
            ],
        ),
    ]
