# Generated by Django 5.1.1 on 2024-09-26 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='image',
        ),
        migrations.AddField(
            model_name='students',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='students',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='academcic_status',
            field=models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='grade',
            field=models.CharField(choices=[('1st Grade', ''), ('2nd Grade', ''), ('3rd Grade', ''), ('4th Grade', ''), ('5th Grade', ''), ('6th Grade', '')], max_length=100),
        ),
    ]
