# Generated by Django 5.1.1 on 2024-10-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='group',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
