# Generated by Django 5.1.1 on 2024-10-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='type_of_student',
            field=models.CharField(choices=[('private student', 'private student'), ('student care network', 'student care network')], default='private student', max_length=100),
        ),
    ]
