# Generated by Django 5.1.1 on 2024-10-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='name',
            new_name='username',
        ),
    ]
