# Generated by Django 5.1.1 on 2024-10-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_students_group_alter_students_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='group',
            field=models.BooleanField(default=False),
        ),
    ]
