# Generated by Django 5.1.1 on 2024-10-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_students_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(default='None', max_length=254),
        ),
        migrations.AddField(
            model_name='students',
            name='guardian_phone_number',
            field=models.CharField(blank=True, default='None', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='name_guardian',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
