# Generated by Django 5.1.1 on 2024-10-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_students_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
