# Generated by Django 5.1.1 on 2024-09-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_students_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='academcic_status',
            new_name='academic_status',
        ),
    ]
