# Generated by Django 5.1.1 on 2024-10-01 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0001_initial'),
        ('students', '0007_alter_students_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Institucion.institution'),
        ),
    ]
