# Generated by Django 5.1.1 on 2024-10-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_students_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='monthly_payent_students',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
