# Generated by Django 5.1.1 on 2024-10-03 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Institucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('luz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agua', models.DecimalField(decimal_places=2, max_digits=10)),
                ('internet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_didactico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patentes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deduccion_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('polizas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uniformes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_medico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alquiler_local', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mensualidad_ninos_privados', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mensualidad_ninos_red_cuido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Institucion.institution')),
            ],
        ),
    ]
