# Generated by Django 5.1.1 on 2024-10-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agua', models.DecimalField(decimal_places=2, max_digits=10)),
                ('internet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_didactico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patentes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deduccion_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('polizas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uniformes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_medico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alquiler_local', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mensualidad_ninos_privados', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mensualidad_ninos_red_cuido', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
