# Generated by Django 5.1.1 on 2024-10-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gastos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
