# Generated by Django 5.1.1 on 2024-10-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gastos', '0003_remove_gasto_balance_gasto_total_alter_gasto_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
